name: Continuous Integration

on: push

jobs:
  build-and-test:
    name: Build the Docker image and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t python .

      - name: Lint Python
        run: |
          run_on_container="docker run --rm -i -v $(pwd):/work python sh -c "
          lint="pycodestyle --show-source --show-pep8 "

          $run_on_container "$lint main.py"

          for module in `ls ./modules/*.py`
          do
            $run_on_container "$lint $module"
          done
